## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.



In [ ]:
# De nou no em queda clar amb l'enunciat si demana que li demanis al usuari el array. AiXi que l'he fet de dos formes
## 1.- Demanant al usuari:

import numpy as np 
# crido al usuari entrar un array d'una dimensió amb nombres separats amb espais
x = np.array(input('Entra un array, de números sencers separats per espais: ').split(), dtype=int)
print(x)
if len(x.shape) > 1:
    print("Error: El array té més d'una dimensió.")

#Defineixo el resum estadístic amb les funcions bàsiques:
def resum_estadistic(x):
    
    result = {}
    result['n'] = len(x) # numero de valors 
    result['min'] = np.min(x) # valor minim 
    result['max'] = np.max(x) # valor màxim
    result['mean'] = np.mean(x) # valor mitjana
    result['median'] = np.median(x) # valor mediana 
    result['std'] = np.std(x) # valor desviació estàndard
    result['var'] = np.var(x) # valor variànça
    return result
    
resultat = resum_estadistic(x)
print(resultat)






In [3]:
## 2.- Posant jo el array/vector 

import numpy as np 
def resum_estadistic(meuarray):
    if len(meuarray.shape) > 1:
        print("Error: La matriu té més d'una dimensió.")
    else:
        print("Resum estadístic:")
        print("Mínim: ", np.min(meuarray))
        print("Màxim: ", np.max(meuarray))
        print("Mitjana: ", np.mean(meuarray))  
        print("Mediana: ", np.median(meuarray))
        print("Desviació estàndard: ", np.std(meuarray))
        print("Variància: ", np.var(meuarray))

# Exemple que li dono jo
meuarray = np.array([25, 2, 62, 4, 101])
resum_estadistic(meuarray)






Resum estadístic:
Mínim:  2
Màxim:  101
Mitjana:  38.8
Mediana:  25.0
Desviació estàndard:  37.84917436351815
Variància:  1432.56


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.



In [5]:
import numpy as np
from numpy import random #de Numpy importo el modul random
R = random.randint(100, size=(5, 5)) #li dic que agafi numeros sencers aleatoris del 1 al 100 i d'un tamany 5x5
print(R)

[[37 76 77 72 15]
 [73 19 34 53  7]
 [17 74 75 39 41]
 [88 63 56  9 13]
 [76 95 31 21 88]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.



In [7]:
import numpy as np
from numpy import random #de Numpy importo el modul random
F = random.randint(100, size=(2, 5)) #li dic que agafi numeros sencers aleatoris del 1 al 100 i d'un tamany 2x5
print(F)
totalcol = np.sum([F], axis=1) #li dic que sumi el axis 1 que e2 el vertical
print("Total per columna:", totalcol) 
totalfil = np.sum([F], axis=2) #li dic que sumi el axis 1 que es el horitzontal
print ("Total per fila:", totalfil) 

[[ 3 42  9 86 72]
 [33 21 79 94  7]]
Total per columna: [[ 36  63  88 180  79]]
Total per fila: [[212 234]]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.


In [15]:
## El coeficient de correlació cuantifica la relació lineal de dos variables entre si, respecte la mitja.
## Els seus valors varien entre el 1 (si te una correlacio lineal perfecte i si incrementen alhora) i el -1 
##(si es totalment a la inversa, quan un puja l'altre baixa)

import numpy as np
def coeficient_correlacio(arraytemperatura, arraypreus): 
   
    
    ## El primer que hem de fer es calcular les mitjanes 
    ## Mitjana de les temperatura
    mitjana_temperatura = np.mean(arraytemperatura)
    mitjana_preus = np.mean(arraypreus)
  
    ## Ara restem cada valor de la mitja 
    temprestantmitja= np.subtract(arraytemperatura, mitjana_temperatura)
    factrestantmitja= np.subtract(arraypreus, mitjana_preus)

    ####### i ara per tenir el numerador de la fórmula: 
    ####### ∑((valor llista 1-mitjana llista 1)X(valor llista 2 -mitjana llista2))

    ## multipliquem els valors d'aquestes dues arrays 
    numerador = np.multiply(temprestantmitja, factrestantmitja)
   
    ## sumem el les diferencies respecte la mitja multiplicades
    total= np.sum(numerador)
    
    ####### i ara per tenir el denominador de la fórmula: 
    ####### √ Σ(((valor llista 1-mitjana llista 1)elevat al quadrat) X(valor llista 2-mitjana llista 2)elevat al quadrat)))
    
    ## primer elevem al quadrat el array que hem restat la mitja de temperatura a la temperatura)
    quadrattemperatura = temprestantmitja ** 2
    quadratfact = factrestantmitja ** 2
    
    ## ara sumem aquests 2 arrays dels quadrats de temperatura i facturació
    totalquadrattemp = np.sum(quadrattemperatura)
    totalquadratfact = np.sum(quadratfact)
    
    ## Els multipliquem 
    totalmultiplicacio = totalquadrattemp * totalquadratfact

    ## i d'aquesta suma li fem l'arrel quadrada
    arrelquadrada = np.sqrt(totalmultiplicacio)
    
    coeficient_correlacio = total / arrelquadrada
    return coeficient_correlacio

###### Per tant el coeficient de correlació d'aquest exemple seria el numerador (total) dividit entre 
##### el denominador, que en aquest cas l'he anomenat (arrelquadrada)

#Posem un exemple amb 2 arrays: temperatura durant els 4 trimestres
arraytemperatura = np.array([12,21,32,9]) 
#I els totals de la factura electrica 
arraypreus = np.array([34,74,120,23]) 
print("La temperatura dels 4 trimestres es:" , arraytemperatura)
print("El preu de la factura dels 4 trimestres es:", arraypreus)

# Cridem a la funció per aquest exemple
exemple=coeficient_correlacio(arraytemperatura, arraypreus)

    
print ("En aquest exemple el coeficient de correlació es gairebé perfecte, molt proper a 1:", exemple)
correlation_coef = np.corrcoef(arraytemperatura, arraypreus)[0, 1]
print("Per veure si es correcte el càlcul manual que he fet, faig la formula en python (np.corroef), Coeficient de correlació:", correlation_coef)
    

La temperatura dels 4 trimestres es: [12 21 32  9]
El preu de la factura dels 4 trimestres es: [ 34  74 120  23]
En aquest exemple el coeficient de correlació es gairebé perfecte, molt proper a 1: 0.9998229303801593
Per veure si es correcte el càlcul manual que he fet, faig la formula en python (np.corroef), Coeficient de correlació: 0.9998229303801592


In [7]:
### Per fer aquest exercici,he fet primer un exemple per veure si me'n sortia i el poso aqui , seguint jo la formula pas a pas :)
 
arraytemperatura = np.array([12,21,32,9]) #Aquesta seria la temperatura durant els 4 trimestres
arraypreus = np.array([34,74,120,23]) #Aquest serien els totals de la factura electrica 
print("La temperatura dels 4 trimestres es:" ,arraytemperatura)
print("El preu de la factura dels 4 trimestres es:",arraypreus)
    

print("Mitjana de la temperatura durant l'any: ", np.mean(arraytemperatura)) 
print("Mitjana de la factura elèctrica durant l'any: ", np.mean(arraypreus)) 
## Ara restem cada valor de la mitja 
temprestantmitja= np.subtract(arraytemperatura, np.mean(arraytemperatura))
factrestantmitja= np.subtract(arraypreus, np.mean(arraypreus))

print("Si li restem la mitja de temp a la temperatura:",temprestantmitja)
print("Si li restem la mitja de preu als preus :",factrestantmitja)
####### i ara per tenir el numerador de la fórmula: 
####### ∑((valor llista 1-mitjana llista 1)X(valor llista 2 -mitjana llista2))

## multipliquem els valors d'aquestes dues arrays 
numerador = np.multiply(temprestantmitja, factrestantmitja)
print ("Les diferencies respecte la mitja multiplicades son:",numerador)
## sumem el les diferencies respecte la mitja multiplicades
total= np.sum(numerador)
print ("Les diferencies respecte la mitja multiplicades i sumades, per tenir el numerador son:",(total))

####### i ara per tenir el denominador de la fórmula: 
####### √ Σ(((valor llista 1-mitjana llista 1)elevat al quadrat) X(valor llista 2-mitjana llista 2)elevat al quadrat)))
    
## primer elevem al quadrat el array que hem restat la mitja de temperatura a la temperatura)
quadrattemperatura = temprestantmitja ** 2
quadratfact = factrestantmitja ** 2
print ("El quadrat de la diferencia de temperatura a la mitja es:", quadrattemperatura)
print ("El quadrat de la diferencia de facturació a la mitja es:", quadratfact)
    
## ara sumem aquests 2 arrays dels quadrats de temperatura i facturació
totalquadrattemp = np.sum(quadrattemperatura)
totalquadratfact = np.sum(quadratfact)
print("El array dels quadrats de temperatura suma:",totalquadrattemp)
print("El array dels quadrats de facturació suma:",totalquadratfact)

## Els multipliquem 
totalmultiplicacio = totalquadrattemp * totalquadratfact
print ("Multipliquem la suma anterior:",totalmultiplicacio)

## i d'aquesta multiplicació li faig l'arrel quadrada (sense importar el modul math)
arrelquadrada = totalmultiplicacio **.5
arrelquadrada2 = np.sqrt(totalmultiplicacio)
print("I fem l'arrel quadrada al total anterior per tenir el total del denominador",arrelquadrada)
print(arrelquadrada2)

###### Per tant el coeficient de correlació d'aquest exemple seria el numerador (total) dividit entre 
##### el denominador, que en aquest cas l'he anomenat (arrelquadrada)

coeficient_correlacio = total / arrelquadrada

print ("En aquest exemple el coeficient de correlació es gairebé perfecte:", coeficient_correlacio, "quan la temperatura puja el preu de la electricitat puja, per tant, podriem dir que les variables estan correlacionades, seria una representació gràfica d'una funció pràcticament lineal")

### comprovo amb la formula a python que el meu càlcul sigui correcte:
correlation_coef = np.corrcoef(arraytemperatura, arraypreus)[0, 1]
print("Per veure si es correcte el càlcul manual, faig la formula en python np.corroef, Coeficient de correlació:", correlation_coef)
    





La temperatura dels 4 trimestres es: [12 21 32  9]
El preu de la factura dels 4 trimestres es: [ 34  74 120  23]
Mitjana de la temperatura durant l'any:  18.5
Mitjana de la factura elèctrica durant l'any:  62.75
Si li restem la mitja de temp a la temperatura: [-6.5  2.5 13.5 -9.5]
Si li restem la mitja de preu als preus : [-28.75  11.25  57.25 -39.75]
Les diferencies respecte la mitja multiplicades son: [186.875  28.125 772.875 377.625]
Les diferencies respecte la mitja multiplicades i sumades, per tenir el numerador son: 1365.5
El quadrat de la diferencia de temperatura a la mitja es: [ 42.25   6.25 182.25  90.25]
El quadrat de la diferencia de facturació a la mitja es: [ 826.5625  126.5625 3277.5625 1580.0625]
El array dels quadrats de temperatura suma: 321.0
El array dels quadrats de facturació suma: 5810.75
Multipliquem la suma anterior: 1865250.75
I fem l'arrel quadrada al total anterior per tenir el total del denominador 1365.741831386884
1365.741831386884
En aquest exemple el co